site_name: 'Parking Plus WPS_LPR'
site_url: '' # Generates a file:// site.
site_dir: 'build/site'
copyright: Copyright &copy; WPS Brasil Ltda. Todos os Direitos Reservados.
use_directory_urls: false
strict: true
theme:
  name: material
  language: pt
  custom_dir: theme
  features:
    - navigation.indexes
    - navigation.sectionsnna
    - navigation.expand
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Tema Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Tema Claro
extra_css:
  - assets/stylesheets/wps-config-avancadas.css
extra:
  version:
    provider: mike # Não usamos mike, geramos versions.json manualmente no deploy.
                   # https://colab.research.google.com/drive/1wShWQsGRfBtQbpsqzplDsiuTwba5mEa9?usp=sharing
nav:
  - Inicio: index.md
  - Configuração:
    - Configuração Sistema Operacional: configuracao_sistema_operacional.md
    - Instalação MQTT: instalacao_mqtt.md
    - Instalação: instalacao.md
    - Execução: execucao.md
    - Erros Comuns: erros.md
    - Rekognition: rekognition.md

